--- 

### 2021 FALL
### DSGA1007

--- 

### HW02
### Due Date: 2021-10-07, 8PM

Firstname: Yoon Tae

Lastname: Park 

E-mail: yp2201@nyu.edu


--- 

Enter your solutions below,  and submit this notebook

### Problem 01 (10 points):

1. 1 (5 points) Write a function that iteratively calculates factorial $n!$ of an integer $n \geq 0$, where $n!=1 \cdot 2 \cdot \dots \cdot n$. Evaluate the function for $n=10$.


1. 2 (5 points) Write a function that recursively calculates factorial $n!$ of an integer $n \geq 0$, where $n!=1 \cdot 2 \cdot \dots \cdot n$. Evaluate the function for $n=10$.


### 1.1 Write a function that iteratively calculates factorial  𝑛!

In [1]:
# 1.1
def factorial_iter(n):
    # if n = 0 then value should be 0! = 1
    if n == 0: return 1
    
    res  = 1
    for i in range(1, n+1):
        res *= i
    return res

factorial_iter(10)

3628800

### 1.2 Write a function that recursively calculates factorial  𝑛!

In [2]:
# 1.2
def factorial_recur(n):
    # if n = 0 then value should be 0! = 1
    if n <= 1: return 1
    else: return n * factorial_recur(n-1)

factorial_recur(10)

3628800

### Problem 02 (50 points)

Let $M$ be a real quadratic matrix, that is, the number of rows and columns are the same. 

2.1 (20 points) Write a function that *recursively* calculates the power of matrix to the exponent $k$ (by the definition of the matrix multiplication). Here $k \geq 0$ is an integer.

```def matrix_mult_rec(M, k):
    return M_to_power
```    
    
2.2 (10 points) What is the number of calls, that is, how many times the function has been called for $k=100$?

2.3 (15 points) Given the same question as the one in 2.2, what is the answer for a general input $k$?

2.4. (5 points) What is the answer for `M=np.ones((5, 5))` and `k=5`?

### 2.1 Write a function that recursively calculates the power of matrix to the exponent k

In [3]:
# 2.1 (20 points) Write a function that recursively calculates the power of matrix to the exponent k

import numpy as np

def power_of_matrix_recur(M, k):
    # if k == 0 then, M^0 = I, so return identity matrix
    if k == 0: return np.eye(M.shape[0])
    
    if k == 1: M_to_power = M       
    else: M_to_power = np.matmul(M, power_of_matrix_recur(M, k-1))
    
    return M_to_power

# example
M = np.array([[1,2],[4,5]])
k = 3

power_of_matrix_recur(M, k)

array([[ 57,  78],
       [156, 213]])

### 2.2 What is the number of calls, that is, how many times the function has been called for k = 100?
### Answer: 100

In [4]:
# 2.2 (10 points) What is the number of calls, that is, how many times the function has been called for k = 100?
# Number of calls: 100

import numpy as np

def power_of_matrix_recur_cnt(M, k, count=1):  
    
    # if k == 0 then, M^0 = I, so return identity matrix
    if k == 0:
        print('Number of calls:', count)
        return np.eye(M.shape[0])
        
    
    if k == 1: 
        M_to_power = M
        print('Number of calls:', count)
        
    else: 
        M_to_power = np.dot(M, power_of_matrix_recur_cnt(M, k-1, count+1))
  
        
    return M_to_power

# example
M = np.array([[1,2],[4,5]])
k = 100

power_of_matrix_recur_cnt(M, k)


Number of calls: 100


array([[  483734416012797425, -7676837031707950280],
       [ 3093070010293651056,  3576804426306448481]])

### 2.3 Given the same question as the one in 2.2, what is the answer for a general input k?
### Answer: Number of calls: k

#### Intuitively, if input k=n , we will call function from function(k=n) to function(k=1)
#### So total number of calls will be k times

### 2.4. What is the answer for M=np.ones((5, 5)) and k=5?
[[625., 625., 625., 625., 625.],  
 [625., 625., 625., 625., 625.],  
 [625., 625., 625., 625., 625.],  
 [625., 625., 625., 625., 625.],  
 [625., 625., 625., 625., 625.]]

In [5]:
# 2.4 code
import numpy as np

def power_of_matrix_recur(M, k):
    # if k == 0 then, M^0 = I, so return identity matrix
    if k == 0: return np.eye(M.shape[0])
    
    if k == 1: M_to_power = M       
    else: M_to_power = np.dot(M, power_of_matrix_recur(M, k-1))
    
    return M_to_power

# example
M = np.ones((5, 5))
k = 5

power_of_matrix_recur(M, k)

array([[625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.]])

### Problem 03 (20 points):

3.1 (5 points) Write a function that performs a bubble sort.(Function from the lecture is accepted)

3.2 (5 points) Write a function that performs a merge sort.(Function from the lecture is accepted)

3.3 (5 points) Generate a random numpy array $a$, of length $n=10000$, where each component is a random number independently and uniformly generated from the interval $[0, 1]$. 

3.4 (5 points) Estimate and print the actual running times for the functions from 3.1 and 3.2 when applied on the array $a$.

**Hint**: In problem 3.4 you are asked to find the actual running time for each of the functions bubble sort and merge sort when applied on the random array $a$. In order to calculate the running time, that is, how long a function takes to run, you can use the following code:

### 3.1 Write a function that performs a bubble sort.(Function from the lecture is accepted)

In [6]:
# 3.1 code
def bubble_sort(arr):
    """sort array: bubble sort"""
    for i in range(len(arr) - 1):
        for j in range(i + 1, len(arr)):
            if arr[i] > arr[j]:
                # swap elements:
                arr[i], arr[j] = arr[j], arr[i]
                
    return arr

In [7]:
arr = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
bubble_sort(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 3.2 Write a function that performs a merge sort.(Function from the lecture is accepted)

In [8]:
# 3.2 code
def merge_sort(arr):
 
    if len(arr) <= 1:
        return arr
    
    # otherwise split into two halves 
    middle = len(arr) // 2
    
    arr_left = arr[: middle]    
    arr_right = arr[middle: ]

    arr_left = merge_sort(arr_left)
    arr_right = merge_sort(arr_right)
    
    return list(merge_two_sorted(arr_left, arr_right))


def merge_two_sorted(left_arr, right_arr):
    
    # init values
    lst_result = []
    left_point, right_point = 0, 0
    
    while left_point < len(left_arr) and right_point < len(right_arr):
        
        if left_arr[left_point] <= right_arr[right_point]:
            lst_result.append(left_arr[left_point])
            left_point += 1
            
        else:
            lst_result.append(right_arr[right_point])
            right_point += 1

    # if we've reached the end of the left list:
    # append the rest of the right list
    if left_point == len(left_arr):
        lst_result += right_arr[right_point: ]
    else:
        lst_result += left_arr[left_point: ]
    
    return lst_result

In [9]:
arr = [3, 7, 4, 9, 5, 2, 6, 1]
merge_sort(arr)

[1, 2, 3, 4, 5, 6, 7, 9]

### 3.3 (5 points) Generate a random numpy array a of length = 10000, where each component is a random number independently and uniformly generated from the interval  [0,1]

In [10]:
# 3.3 (5 points) Generate a random numpy array a of length = 10000,
# where each component is a random number independently and uniformly generated from the interval  [0,1]

x = np.random.rand(10000, )
print(x)

[0.91087537 0.0683837  0.04565826 ... 0.6802513  0.82188066 0.53575747]


### 3.4 (5 points) Estimate and print the actual running times for the functions from 3.1 and 3.2 when applied on the array a.

In [11]:
# actual running times for 3.1
import datetime

arr = [10, 11, 12, 13, 9, 8, 7, 6, 5, 4, 3, 2, 1]

start_time =  datetime.datetime.now()
# function
bubble_sort(arr)
end_time =  datetime.datetime.now()
run_time = end_time - start_time
print(run_time)

0:00:00.000046


In [12]:
# actual running times for 3.2
import datetime

arr = [10, 11, 12, 13, 9, 8, 7, 6, 5, 4, 3, 2, 1]

start_time =  datetime.datetime.now()
# function
merge_sort(arr)
end_time =  datetime.datetime.now()
run_time = end_time - start_time
print(run_time)

0:00:00.000053



### Problem 04 (20 points)


The provided file 'nba2020.csv' contains the schedules and information of the NBA games for 2020. Using the unix commands, covered in Lecture04, write scripts which will display:
    
4.1 (5 points) a unique list of NBA teams, provided in the file; (you can use either column "Visitor" or column "Home")

4.2 (5 points) the number of those NBA teams;

4.3 (5 points) a unique list of the times -- provided in the file -- when the NBA matches were played;

4.4 (5 points) the number of these unique times.

**Important:** to skip the header of file you can use: 
    
`!tail -n+2 nba2020.csv`


Since,

``-n, --lines=[+]NUM       output the last NUM lines, instead of the last 10;
                             or use -n +NUM to output starting with line NUM``
        
        
**Hint:** Problems 4.3 and 4.4 are asking for the list and unique times in the provided dataset/file. There is a column "Start (ET)" in the dataset, and you should process this column. For example "3:30p" is one of these times.  For this, you can use the "cut" command and the flag "-f" as described in class. 

### 4.1 (5 points) a unique list of NBA teams, provided in the file; (you can use either column "Visitor" or column "Home")

In [13]:
!tail -n+2 nba2020.csv |cut -d "," -f 3 | sort | uniq | sed '/^$/d'

Atlanta Hawks
Boston Celtics
Brooklyn Nets
Charlotte Hornets
Chicago Bulls
Cleveland Cavaliers
Dallas Mavericks
Denver Nuggets
Detroit Pistons
Golden State Warriors
Houston Rockets
Indiana Pacers
Los Angeles Clippers
Los Angeles Lakers
Memphis Grizzlies
Miami Heat
Milwaukee Bucks
Minnesota Timberwolves
New Orleans Pelicans
New York Knicks
Oklahoma City Thunder
Orlando Magic
Philadelphia 76ers
Phoenix Suns
Portland Trail Blazers
Sacramento Kings
San Antonio Spurs
Toronto Raptors
Utah Jazz
Washington Wizards


### 4.2 (5 points) the number of those NBA teams;

In [14]:
!tail -n+2 nba2020.csv | cut -d "," -f 3  | sort | uniq | sed '/^$/d' | wc -l

      30


### 4.3 (5 points) a unique list of the times -- provided in the file -- when the NBA matches were played;

In [15]:
!tail -n+2 nba2020.csv | cut -d "," -f 2 | sort | uniq | sed '/^$/d'

10:00p
10:30p
3:30p
5:00p
6:00p
7:00p
7:30p
8:00p
8:30p
9:00p
9:30p


### 4.4 (5 points) the number of these unique times.

In [16]:
!tail -n+2 nba2020.csv | cut -d "," -f 2 | sort | uniq | sed '/^$/d' | wc -l

      11
